### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'input_tensor'

### ISSUE THREAD

**Issue by DawnChou** [yjxiong/tsn-pytorch#103]
`Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 166, in train
    output = model(input_var)
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zouyiping/twostream/tsn-pytorch/models.py", line 208, in forward
    output = self.consensus(base_out)
  File "/home/zouyiping/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zouyiping/twostream/tsn-pytorch/ops/basic_ops.py", line 49, in forward
    return SegmentConsensus(self.consensus_type, self.dim)(input)
TypeError: forward() missing 1 required positional argument: 'input_tensor'
`

Has someone met the same problem as me? I've checked the `SegmentConsensus` and I can't figure out why this error printed

**Comment by giannispic** [comment]
Yes ia have the same issue. Did you find a fix?

**Comment by skyisyourlimit** [comment]
I have the same issue. Did you find a fix?

**Comment by skyisyourlimit** [comment]
> Yes ia have the same issue. Did you find a fix?

Did you find?
