### ISSUE TITLE
testing process met error.

### ISSUE THREAD

**Issue by qijiezhao** [yjxiong/tsn-pytorch#13]
I run with the command: 
`CUDA_VISIBLE_DEVICES=2,3 python test_models.py ucf101 Flow data/ucf101_flow_val_split_1.txt ucf101_flow_bninception_flow_checkpoint.pth.tar --arch BNInception --save_score=flow_bninception --flow_pref flow_ --workers=1`

**The output content is as follows:**
```
video 160 done, total 161/3783, average 3.05683402393 sec/video
video 161 done, total 162/3783, average 3.04620183986 sec/video
video 162 done, total 163/3783, average 3.05641095039 sec/video
video 163 done, total 164/3783, average 3.04159315766 sec/video
video 164 done, total 165/3783, average 3.06657971469 sec/video
video 165 done, total 166/3783, average 3.05109782535 sec/video
video 166 done, total 167/3783, average 3.06426371786 sec/video
video 167 done, total 168/3783, average 3.04766791633 sec/video
video 168 done, total 169/3783, average 3.06247991077 sec/video
video 169 done, total 170/3783, average 3.04995046503 sec/video
Traceback (most recent call last):
  File "test_models.py", line 125, in <module>
    for i, (data, label) in data_gen:
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 187, in __next__
    return self._process_next_batch(batch)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/S2/MI/zqj/video_classification/tsn-pytorch/dataset.py", line 99, in __getitem__
    return self.get(record, segment_indices)
  File "/S2/MI/zqj/video_classification/tsn-pytorch/dataset.py", line 107, in get
    seg_imgs = self._load_image(record.path, p)
  File "/S2/MI/zqj/video_classification/tsn-pytorch/dataset.py", line 51, in _load_image
    x_img = Image.open(os.path.join(directory, self.image_tmpl.format('x', idx))).convert('L')
  File "/opt/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2477, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '../data/ucf101/flows_tvl1/v_Skijet_g04_c03/flow_x_00000.jpg'

THCudaCheckWarn FAIL file=/pytorch/torch/lib/THC/THCStream.cpp line=50 error=29 : driver shutting down
```

**Comment by qijiezhao** [comment]
actually, the id of my image list is from 1 to n, not 0.
After I met this error, then I add a try+except command to output variable p and indices when an error appears.  Its output content is as follows:
`0 [ 1  1  1  1  1  1  0  0  0  0  0  0 -1 -1 -1 -1 -1 -1 -1 -2 -2 -2 -2 -2 -2]
`

Can you help me figure out where is the bug? Thank you!

**Comment by qijiezhao** [comment]
solved

**Comment by ntuyt** [comment]
@qijiezhao I encounter the same error, how do you solve it?

**Comment by szu-lqt** [comment]
Hi, @qijiezhao   The same problem I meet, could you please give your file of ucf101_flow_val_split_1.txt  and  dataset.py  to me , thanks a lot!  my e-mail is 1253955013@qq.com
