### ISSUE TITLE
报错求助magic_number = pickle_module.load(f, **pickle_load_args) _pickle.UnpicklingError: invalid load key, '<'.（困扰我很久了救救孩子吧））

### ISSUE THREAD

**Issue by wys2929** [yjxiong/tsn-pytorch#133]

**Comment by wys2929** [comment]
在训练时报的错,具体报错如下
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    main()
  File "main.py", line 41, in main
    consensus_type=args.consensus_type, dropout=args.dropout, partial_bn=not args.no_partialbn)
  File "/home/usr/project1/tsn-pytorch/models.py", line 39, in __init__
    self._prepare_base_model(base_model)
  File "/home/usr/project1/tsn-pytorch/models.py", line 82, in _prepare_base_model
    self.base_model = getattr(torchvision.models, base_model)(True)
  File "/home/usr/anaconda3/envs/TEST1/lib/python3.7/site-packages/torchvision/models/resnet.py", line 277, in resnet101
    **kwargs)
  File "/home/usr/anaconda3/envs/TEST1/lib/python3.7/site-packages/torchvision/models/resnet.py", line 227, in _resnet
    progress=progress)
  File "/home/usr/anaconda3/envs/TEST1/lib/python3.7/site-packages/torch/hub.py", line 495, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/usr/anaconda3/envs/TEST1/lib/python3.7/site-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/usr/anaconda3/envs/TEST1/lib/python3.7/site-packages/torch/serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by ck321123** [comment]
你好，请问你解决了嘛，我现在也有这个问题，完全不知道怎么解决，您可以帮助我嘛？
