### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by Nandan532189** [yjxiong/tsn-pytorch#39]
While testing the RGBDiff model using the command 
****python test_models.py ucf101 RGBDiff /media/sda/nandan/data/ucf101_rgb_val_split_1.txt ucf101_bninception__rgbdiff_checkpoint.pth.tar --arch BNInception --save_scores SCORE_UCF101_1_RGBDIFF --workers=2****
I'm getting this error 
Traceback (most recent call last):
  File "test_models.py", line 130, in <module>
    rst = eval_video((i, data, label))
  File "test_models.py", line 117, in eval_video
    rst = net(input_var).data.cpu().numpy().copy()
  File "/home/nandan/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nandan/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 73, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/nandan/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 83, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/nandan/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCStorage.cu:58

I'm using two K40 GPU with each global memory capacity 4742MiB.

**Comment by Nandan532189** [comment]
@yjxiong : I found that runtime memory problem can be solved either by reducing **--test_crops** size or by reducing **--test_segments** size . My question is which one to prefer ? I mean which one won't affect test accuracy ?

**Comment by wuxiaomin0110** [comment]
@Nandan532189 
Have you solved the "RuntimeError: cuda runtime error (2) : out of memory "?
What's your pytorch version? Thank you!

**Comment by wuxiaomin0110** [comment]
@yjxiong 
Hi   What's your pytorch version of this code?  I set the "workers" as 1 or 2, there will occur an error of "RuntimeError: cuda runtime error (2) : out of memory ", while I set the "workers" as 4, there will occur an error of  "Traceback (most recent call last):
  File "test_models.py", line 128, in <module>
    rst = eval_video((i, data, label))
  File "test_models.py", line 116, in eval_video
    rst = net(input_var).data.cpu().numpy().copy()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 56, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 67, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return tuple(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter(target_gpus, dim=dim)(obj)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 59, in forward
    streams = [_get_stream(device) for device in self.target_gpus]
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 85, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range".
Do you have some advises?

**Comment by wj320** [comment]
I have met the same problem. How did you solve it? @Nandan532189

**Comment by yjxiong** [comment]
The test_crops is the preferred one. It does not lead to a drastic decrease in accuracy.
