### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by gwh0112** [yjxiong/tsn-pytorch#46]
When I run the training script, I encounter the following error:

Downloading: "https://yjxiong.blob.core.windows.net/models/bn_inception-9f5701afb96c8044.pth" to /mnt/lustre/ganweihao/.torch/models/bn_inception-9f5701afb96c8044.p
th                                                                              
                                                                                
Initializing TSN with base model: BNInception.                                  
TSN Configurations:                                                                       
    input_modality:     RGB                                                                   
    num_segments:       3                                                                      
    new_length:         1                                                                      
    consensus_module:   avg                                                                    
    dropout_ratio:      0.8                                                                    
                                                                                               
Traceback (most recent call last):                                                               
  File "main.py", line 301, in <module>                                                           
    main()                                                                                         
  File "main.py", line 35, in main                                                                   
    consensus_type=args.consensus_type, dropout=args.dropout, partial_bn=not args.no_partialbn)         
  File "/mnt/lustre/ganweihao/codes/tsn-pytorch/models.py", line 39, in __init__                    
    self._prepare_base_model(base_model)                                                                      
  File "/mnt/lustre/ganweihao/codes/tsn-pytorch/models.py", line 96, in _prepare_base_model                    
    self.base_model = getattr(tf_model_zoo, base_model)()                                                      
  File "/mnt/lustre/ganweihao/codes/tsn-pytorch/tf_model_zoo/bninception/pytorch_load.py", line 35, in __init__                 
    self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))                                                             
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 56, in load_url
    _download_url_to_file(url, cached_file, hash_prefix)                                                                                    
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/model_zoo.py", line 61, in _download_url_to_file
    u = urlopen(url)                                                                              
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)                                                         
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 429, in open 
    response = self._open(req, data)                                                                 
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 447, in _open     
    '_open', req)                                                               
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)                                                                                
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)                                                                           
  File "/mnt/lustre/ganweihao/anaconda3/envs/python27/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)                                             
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>

Any idea to solve this?
Many thanks.

**Comment by gwh0112** [comment]
I got it. It's my connection problem

**Comment by bixiwen** [comment]
Do you have solved it?I have the same problem.Thank you

**Comment by gwh0112** [comment]
@bixiwen  In my case, there is no internet connection on the computation node in my server. You can download the model manually.

**Comment by curry111** [comment]
@gwh0112  Hi :sweat_smile: :sweat_smile: I'm sorry for the late replay. How did you do it manually.   
I downloaded the file `https://download.pytorch.org/models/vgg16-397923af.pth`  
But I don't know what I should do next. How can I use it when I call the function `vgg16()`

**Comment by Nada-gh** [comment]
@curry111 Did you get a solution for that?! I downloaded Resnet50 model manually but do not know how to forward!
