### ISSUE TITLE
Testing Procedure is not well explained

### ISSUE THREAD

**Issue by lacasanostra12** [yjxiong/tsn-pytorch#57]
Hello, I added a different dataset to the implementation and trained with flow features, now trying to test network for the flow model.

Testing procedure is given as:

> python test_models.py ucf101 RGB <ucf101_rgb_val_list> ucf101_bninception_rgb_checkpoint.pth \
   --arch BNInception --test_crops 1 --save_scores <score_file_name>

However, for the test list argument

> <ucf101_rgb_val_list>

If I use the validation list which I used previously for training the network gives me an error such as : 

> Traceback (most recent call last):
  File "test_models.py", line 130, in <module>
    rst = eval_video((i, data, label))
  File "test_models.py", line 118, in eval_video
    rst = net(input_var).data.cpu().numpy().copy()
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 69, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 80, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 38, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 31, in scatter
    return scatter_map(inputs)
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 73, in forward
    streams = [_get_stream(device) for device in ctx.target_gpus]
  File "/home_nfs/Turcan/.conda/envs/mytorch/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 100, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range

So my question is what kind of information should **test_list** argument include or is something wrong with my testing procedure ?

The Code Run:

>  python test_models.py AFFW Flow data/AFFW_flow_test.txt AFFW_shortclips_gettingbetter__flow_checkpoint.pth.tar --arch BNInception --save_scores AFFWtest

The test txt file is formatted such as : 

> /home/shared_for_databases/AFFW_shortclips_test_set/214_4.avi 510 0
   /home/shared_for_databases/AFFW_shortclips_test_set/116_3.avi 503 1
    .
    .

**Comment by Mohamad73** [comment]
Hello, 
I am getting the same error, were you able to solve it. I would appreciate your help

**Comment by Mohamad73** [comment]
Any suggestion on solving it?
