### ISSUE TITLE
Error: return int(self._data[2]) IndexError: list index out of range

### ISSUE THREAD

**Issue by Mohamad73** [yjxiong/tsn-pytorch#59]
I am getting this error. I uploaded the ucf_101_rgb_train_list.txt, I am suspecting that there is something wrong with it. 
[ucf101_rgb_train_list.txt](https://github.com/yjxiong/tsn-pytorch/files/2318560/ucf101_rgb_train_list.txt)

Traceback (most recent call last):
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\main.py", line 301, in <module>
    main()
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\main.py", line 157, in train
    for i, (input, target) in enumerate(train_loader):
  File "C:\Users\mab73\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\mab73\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "C:\Users\mab73\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\mab73\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\dataset.py", line 101, in __getitem__
    return self.get(record, segment_indices)
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\dataset.py", line 115, in get
    return process_data, record.label
  File "C:\Users\mab73\Desktop\tsn-pytorch-master\dataset.py", line 23, in label
    return int(self._data[2])
IndexError: list index out of range

**Comment by nuppt** [comment]
Hi, @Mohamad73 ,for all I know, each line the file list should be three terms, not only two.

Here is a reference segment from https://github.com/yjxiong/temporal-segment-networks.git:

...
Construct file lists for training and validation
[back to top]

The data feeding in training relies on VideoDataLayer in Caffe. This layer uses a list file to specify its data sources. Each line of the list file will contain **a tuple of extracted video frame path, video frame number, and video groundtruth class**. A list file looks like

**video_frame_path 100 10**
**video_2_frame_path 150 31**
...

**Comment by Mohamad73** [comment]
Got it! Thank you

**Comment by yjxiong** [comment]
@nuppt Thanks for the help.
Closing this. Please feel free to reopen it if you meet any further problem.

**Comment by Mohamad73** [comment]
Hello, I am getting this error when I run `python build_file_list.py ucf101 /home/mohamad/temporal-segment-networks-master` to build the ucf101_rgb_train_list. I am getting 
 `parse frames under folder /home/mohamad/temporal-segment-networks-master/UCF-101-Jpegs/
0 videos parsed
frame folder analysis done
writing list files for training/testing
Traceback (most recent call last):
  File "build_file_list.py", line 38, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/mohamad/temporal-segment-networks-master/pyActionRecog/benchmark_db.py", line 58, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/mohamad/temporal-segment-networks-master/pyActionRecog/benchmark_db.py", line 48, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'`
ANY IDEA?? PLZ

**Comment by Mohamad73** [comment]
By the way, is it a must to have optical flow frames?

**Comment by yjxiong** [comment]
Your videos frames are not present under the folder you specified. They must be in “root_folder/video_name” structure

**Comment by Mohamad73** [comment]
Thank you sir!!!

**Comment by sucaohan** [comment]
hello,sir,I have a same problem to u.when i run  bash scripts/build_file_list.sh hmdb51 /home/ubuntu-507/Downloads/LYY/datasets/hmdb51_feature,
processing dataset hmdb51
parse frames under folder /home/ubuntu-507/Downloads/LYY/datasets/hmdb51_feature/brush_hair
0 videos parsed
frame folder analysis done
writing list files for training/testing
Traceback (most recent call last):
  File "tools/build_file_list.py", line 40, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/ubuntu-507/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 59, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/ubuntu-507/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 49, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: '20060723sfjffsomelikeitwarmed_eat_u_cm_np1_fr_med_2'
 can u tell me how to change it?i guess it's wrong with the input directory,but i don't know what is the root_folder?

**Comment by yhc1994** [comment]
> Hi, @Mohamad73 ,for all I know, each line the file list should be three terms, not only two.
> 
> Here is a reference segment from https://github.com/yjxiong/temporal-segment-networks.git:
> 
> ...
> Construct file lists for training and validation
> [back to top]
> 
> The data feeding in training relies on VideoDataLayer in Caffe. This layer uses a list file to specify its data sources. Each line of the list file will contain **a tuple of extracted video frame path, video frame number, and video groundtruth class**. A list file looks like
> 
> **video_frame_path 100 10**
> **video_2_frame_path 150 31**
> ...

Hi,

I have edited my list file under the for mat **video_frame_path 100 10**
But I will randomly get new error.
It return int(self._data[1]) IndexError rather than self._data[2]
The code is attached.

`clipping gradient: 26.06275177001953 with coef 0.7673786878585815
clipping gradient: 20.03441047668457 with coef 0.9982824325561523
Epoch: [4][400/417], lr: 0.00100        Time 0.392 (0.424)      Data 0.000 (0.019)      Loss 0.5160 (0.7827)    Prec@1 87.500 (78.554)  Prec@5 96.875 (94.966)
clipping gradient: 20.379911422729492 with coef 0.981358528137207
clipping gradient: 23.24842071533203 with coef 0.8602734804153442
clipping gradient: 21.31159782409668 with coef 0.938456118106842
clipping gradient: 23.550817489624023 with coef 0.8492274284362793
clipping gradient: 25.323293685913086 with coef 0.7897866368293762
clipping gradient: 21.75693702697754 with coef 0.919247031211853
clipping gradient: 21.740734100341797 with coef 0.9199321269989014
clipping gradient: 45.87702178955078 with coef 0.43594807386398315
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "main.py", line 301, in <module>
    main()
  File "main.py", line 128, in main
    prec1 = validate(val_loader, model, criterion, (epoch + 1) * len(train_loader))
  File "main.py", line 213, in validate
    for i, (input, target) in enumerate(val_loader):
  File "D:\Anaconda3\envs\dissertation\lib\site-packages\torch\utils\data\dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "D:\Anaconda3\envs\dissertation\lib\site-packages\torch\utils\data\dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "D:\Anaconda3\envs\dissertation\lib\site-packages\torch\utils\data\dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Anaconda3\envs\dissertation\lib\site-packages\torch\utils\data\dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\Developments\Dissertation\tsn-pytorch\dataset.py", line 95, in __getitem__
    segment_indices = self._sample_indices(record) if self.random_shift else self._get_val_indices(record)
  File "D:\Developments\Dissertation\tsn-pytorch\dataset.py", line 76, in _get_val_indices
    if record.num_frames > self.num_segments + self.new_length - 1:
  File "D:\Developments\Dissertation\tsn-pytorch\dataset.py", line 19, in num_frames
    return int(self._data[1])
IndexError: list index out of range
`
