### ISSUE TITLE
trained models in pytorch

### ISSUE THREAD

**Issue by nationalflag** [yjxiong/tsn-pytorch#6]
Would you share the trained models in pytorch?

**Comment by yjxiong** [comment]
Good point. I will give the models on UCF101 split1 for your references.

**Comment by nationalflag** [comment]
Thanks! I‘m very expect for it!

**Comment by gss-ucas** [comment]
@yjxiong Hi, thank you for your wonderful job!!!
Could you tell me where to download the pretrained models in pytorch???

**Comment by ntuyt** [comment]
@yjxiong Hi, Xiong.
Also need the pretrained models in pytorch.
Thanks so much!

**Comment by yjxiong** [comment]
We don't have all pretrained UCF101/HMDB51 models in the  PyTorch format for download. I can convert the Caffe pretraned models in the original TSN codebase to PyTorch format in next few weeks.

**Comment by gss-ucas** [comment]
I have finished a complicated script for transferring caffemodel to pytorch. When I use the transferred pytorchmodel on tsn-pytorch code, I have got the same result as paper. If you desire pytorchmodel immediately, please see ‘’https://github.com/gss-ucas/caffe2pytorch-tsn'‘

**Comment by ntuyt** [comment]
@gss Seems that the link you share is broken.

**Comment by ntuyt** [comment]
@gss-ucas Thanks

**Comment by scenarios** [comment]
@yjxiong Thanks for your efforts.
I recently parsed your pretrained caffemodel (ucf split 1) into tensorflow with google protobuf. And I constructed the rgb stream in tensorflow with every layer identical to the one in your caffe train-val protocal. However, the accuracy is still 10% lower than the caffe version. (Padding strategy is different in caffe and tf, but it is properly solved by manually padding in tf.)
I'm wondering is there any other details I should take care? Thanks!

BTW, @gss-ucas  it seems that maxpooling with floor mode is used in your implementation, which is not consistent with the caffe version. But strange you can still reproduce the results lol

**Comment by victorhcm** [comment]
@scenarios what data augmentations are you using? Is your model
BN-Inception (+TSN)? If so, are you enabling partial BN when finetuning?

Victor Hugo

**Comment by scenarios** [comment]
@victorhcm Actually I'm not finetuning. I simply initialize the my BN-Inception model in tensorflow with the parameter released by TSN (it is a caffemodel, I parsed it using protobuf) and do online test without any training. At the very begining, the accuracy is only around 0.6 with 3 segment. Then I realized there is a slight difference between caffe and tensorflow in padding (both for convolution and pooling). After modifying the pading , the accuracy increased to 71%, which is still 10% lower than the caffe resuts.(I test the same model with TSN home-brewed caffe and got 0.81 accuracy with 3 segment).
I have double-checked every layer and for sure they are identical to the model definition in train_val protocal in TSN (or there must be errors when loading the parameter).
Still confused why..

**Comment by scenarios** [comment]
@victorhcm And for testing, I resize the frame to 256x340 and central crop to 224x224. Mean is subtracted. And I also change rgb image to bgr format for consistence.

**Comment by JiqiangZhou** [comment]
@yjxiong  I use the default command you provided to train my RGBDiff、RGB and Flow model with tsn-pytorch, could you please tell me if they were initialized on ImageNet?

**Comment by yjxiong** [comment]
@JiqiangZhou Yes.

**Comment by JiqiangZhou** [comment]
@yjxiong thank you! I will read the code carefully.

**Comment by liu666666** [comment]
I run the default command and obtain a lower performance than the paper(85.12 vs 85.7). The model is available at http://pan.baidu.com/s/1eSvo8BS
. Hope it helps.

**Comment by utsavgarg** [comment]
@yjxiong Even I trained the models using default settings for split-1 of the UCF-101 dataset and am getting a lower performance than reported. Below are the numbers I got:

RGB - 85.57%
Flow - 84.26%
RGB + Flow - 90.44%

What could be the reason for this?

**Comment by yjxiong** [comment]
@utsavgarg 
Please use the instruction in Caffe TSN to extract optical flow.

**Comment by utsavgarg** [comment]
@yjxiong I had done that, I extracted optical flows using the `extract_optical_flow.sh` script included with Caffe TSN but I used `extract_cpu` instead of `extract_gpu` in `build_of.py`, will that cause this difference in performance?

**Comment by yjxiong** [comment]
Yes that's the problem. Always use `extract_gpu`. The optical flow algorithm you need is not available in `extract_cpu`.

**Comment by SmartPorridge** [comment]
@utsavgarg `extract_cpu`, use TVL1 optical flow and it leads to a better accuracy. I did a experiment for that.

**Comment by SmartPorridge** [comment]
@utsavgarg `extract_gpu` use TVL1 optical flow and it leads to a better accuracy. I did a experiment for that.

**Comment by utsavgarg** [comment]
Okay thanks.

**Comment by mangdian** [comment]
Did anyone get the pytorch pretrained models on ActivityNet or Kinetics?
@yjxiong @nationalflag @gss-ucas @ntuyt @scenarios

**Comment by Ivorra** [comment]
Hello,
are there any available models trained in ufc? 

Thanks!

**Comment by gss-ucas** [comment]
@Ivorra
please see [https://github.com/gss-ucas/caffe2pytorch-tsn]

**Comment by Ivorra** [comment]
@gss-ucas Thanks for kindly answering,  I am having troubles in "test_models.py", as after loading your model "ucf101_rgb.pth" it seems that some keys do not exist, for with the command example:

`python test_models.py ucf101 RGB <ucf101_rgb_val_list> ucf101_rgb.pth --arch BNInception --save_scores <score_file_name>`

I get the error:

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py:514: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
Traceback (most recent call last):
  File "test_models.py", line 54, in <module>
    print("model epoch {} best prec@1: {}".format(checkpoint['epoch'], checkpoint['best_prec1']))
KeyError: 'epoch'
 
And if I comment that line, another key error appears:

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py:514: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
Traceback (most recent call last):
  File "test_models.py", line 56, in <module>
    base_dict = {'.'.join(k.split('.')[1:]): v for k,v in list(checkpoint['state_dict'].items())}
KeyError: 'state_dict'

Thanks!

**Comment by poppingcode** [comment]
I wonder how to fuse?  who  can  help me？ thanks

**Comment by gss-ucas** [comment]
@lvorra please read README.md carefully in https://github.com/gss-ucas/caffe2pytorch-tsn. And if you have any question, please ask it in there.

**Comment by Ivorra** [comment]
@poppingcode I followed the [instructions](https://github.com/yjxiong/temporal-segment-networks#testing-provided-models) at the original TSN repository. Just copied the [eval_scores.p](https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_scores.py)y file provided there in conjunction with the folder [pyActionRecog](https://github.com/yjxiong/temporal-segment-networks/tree/master/pyActionRecog) which is needed as a dependency. 

Hope it works fine for you!

**Comment by SinghGauravKumar** [comment]
@gss-ucas Hi, did you manage to convert kinetics pretrained models (as shown at http://yjxiong.me/others/kinetics_action/ ) to pytorch too?

**Comment by Ivorra** [comment]
Maybe this Caffe --> model convertor is worth looking at:

https://github.com/marvis/pytorch-caffe

**Comment by SinghGauravKumar** [comment]
@Ivorra Installing the right version of caffe has been a pain. Wondering if @yjxiong , @gss-ucas can provide the kinetics pretrained models for pytorch?

**Comment by fmthoker** [comment]
@SinghGauravKumar  can you provide any guidance about the installation of a right version of Caffe...would be really helpful?

**Comment by sipan17** [comment]
@yjxiong is there any pre-trained model on HMDB51 dataset?

**Comment by shuangshuangguo** [comment]
@sipan17 Please see https://github.com/shuangshuangguo/caffe2pytorch-tsn

**Comment by TiJoy** [comment]
> I run the default command and obtain a lower performance than the paper(85.12 vs 85.7) on the rgb stream. The model is available at http://pan.baidu.com/s/1eSvo8BS
> . Hope it helps.

I have a question that there is a error when I decompression my ucf101_bninception__rgb_checkpoint.pth.tar.
`tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors`
what should I do?

**Comment by yjxiong** [comment]
@TiJoy 

You don't need to uncompress it. `pth.tar` is just the extension of model files used by PyTorch.

**Comment by TiJoy** [comment]
> @TiJoy
> 
> You don't need to uncompress it. `pth.tar` is just the extension of model files used by PyTorch.

Thank you, I know that I just need to delet `.tar` in its file name.

**Comment by linshuheng6** [comment]
@Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.

Thank you!

**Comment by linshuheng6** [comment]
@liu666666  Hello, I have tried your model but I only get the result of 76.13 for RGB. I think there is something wrong with my code. Could you please give me your parameter of args?

**Comment by cbasemaster** [comment]
hallo i use kinetics pretrain shared above to be fined tune with ucf split 1, however the accuracy is still low like this, Testing Results: Prec@1 56.732 Prec@5 84.967 Loss 2.49515

while training is

Loss 0.2026 (0.3246)	Prec@1 93.750 (90.549)	Prec@5 98.438 (97.904)
after 80 epoch 64 sized minibatch

do you know where is gone wrong here?

![Screen Shot 2019-08-02 at 18 44 10](https://user-images.githubusercontent.com/10804898/62361356-d2809300-b555-11e9-9d39-52b50e817f5f.png)

**Comment by imnotk** [comment]
> @Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.
> 
> Thank you!

I can only get 78% RGB accuracy using split 1 on UCF101, how do you solve it?  It's very wierd.

**Comment by linshuheng6** [comment]
> > @Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.
> > Thank you!
> 
> I can only get 78% RGB accuracy using split 1 on UCF101, how do you solve it? It's very wierd.



> > @Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.
> > Thank you!
> 
> I can only get 78% RGB accuracy using split 1 on UCF101, how do you solve it? It's very wierd.

I have not change the data sample in the original code. In the original code the data sample was set as [b*crops,c,h,w], What do you mean [b,t,c,h,w]?
I only found the input_mean = [104,117,123]. The input_std has not been found. Could you please provide it to me? Thank you!

**Comment by linshuheng6** [comment]
@imnotk by the way, the trainded model give 97.8% accuracy on the training set ucf101-split1. It means this model and basic parameter in the code is useful? I still have not found the reason why it work badly on the test set...

**Comment by nanhui69** [comment]
@liu666666 have you extract the ucf101 RGB-Frames by 'bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER'  when i do it ,enconter lots of problems, could you share the RGB-frame dataset of ucf101 ?

**Comment by nanhui69** [comment]
@linshuheng6  Are you reproduce the TSN project successful ?could i communicate with you by QQ or others？

**Comment by linshuheng6** [comment]
@nanhui69 I used the ffmpeg command to extract the frame in the video, not the script provided by the quthor. I have not reproduced TSN, I just used the source code and run the test document. You can contact me by send email to huins_shu@sjtu.edu.cn.

**Comment by Shumpei-Kikuta** [comment]
> > @Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.
> > Thank you!
> 
> I can only get 78% RGB accuracy using split 1 on UCF101, how do you solve it? It's very wierd.

@imnotk Have you solved this problem?
I just got the same accuracy 78% for RGB using split 1 on UCF101.

**Comment by linshuheng6** [comment]
@Shumpei-Kikuta  I have sovled this problem by extract frames from video by opencv command instead of ffmpeg

**Comment by Shumpei-Kikuta** [comment]
@linshuheng6 Thank you for sharing.
I got stuck in extracting frames as that repository shows, so I've used this one: http://ftp.tugraz.at/pub/feichtenhofer/tsfusion/data
Anyway, thank you!

**Comment by imnotk** [comment]
> > > @Ivorra Hello, I have tried the converted models from caffe. But I only got 75% accuracy on ucf101-split1 with only RGB model. Could you share the parameters of args with me? And how did you extract frame from video? I just used ffmepg command.
> > > Thank you!
> > 
> > 
> > I can only get 78% RGB accuracy using split 1 on UCF101, how do you solve it? It's very wierd.
> 
> @imnotk Have you solved this problem?
> I just got the same accuracy 78% for RGB using split 1 on UCF101.

No, always get stuck in 78% with resnet in pytorch.

**Comment by uname0x96** [comment]
Hi @yjxiong, I'm tried to convert PyTorch model to onnx model. But I got this error: RuntimeError: Attempted to trace SegmentConsensus, but tracing of legacy functions is not supported. Have any solution for this?

**Comment by YuLengChuanJiang** [comment]
@imnotk @Shumpei-Kikuta @linshuheng6  hello，i want to run main.py. But I don't know how it loads the frames which were extracted before. The <ucf101_flow_train_list> is referred to trainlist01.txt path, is that true? Thanks for any help!

**Comment by shijubushiju** [comment]
@YuLengChuanJiang Hello, I am also doing this, can we contact and communicate

**Comment by Shumpei-Kikuta** [comment]
@YuLengChuanJiang @shijubushiju Have you extracted optical flow from videos and make lists?
Otherwise, you should follow [this repository](https://github.com/yjxiong/temporal-segment-networks) to do this.
This repo is the original version of TSN, coded by Caffe.

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta If I want to make my own dataset for action recognition, what kind of list should I generate

**Comment by YuLengChuanJiang** [comment]
Of course, I also start to do this topic, very glad to communicate with you. Have you run this program successfully?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shijubushiju"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:57
收件人:&nbsp;"yjxiong/tsn-pytorch"<tsn-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"君临天下"<1058847739@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/tsn-pytorch] trained models in pytorch (#6)




@YuLengChuanJiang Hello, I am also doing this, can we contact and communicate

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju You should follow [here](https://github.com/yjxiong/temporal-segment-networks#construct-file-lists-for-training-and-validation).
Specifically, the trainlist file should be formed as frame path, video frame number, and video groundtruth class.

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta Thank you. I have carefully read relevant documents and am ready to give it a try. Thank you very much for your advice

**Comment by shijubushiju** [comment]
@YuLengChuanJiang My email is 1462753330@qq.com, we can discuss these issues

**Comment by YuLengChuanJiang** [comment]
um,&nbsp; I have extracted optical flow from videos through the opencv4.1.0 and the build_of.py. But, I don't make lists because I have some trouble using Caffe on the school's server. I don't know if the list is tranlist01.txt doc. Is it such "ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01.avi" doc? Thanks a lot.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"skhiuk"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午3:03
收件人:&nbsp;"yjxiong/tsn-pytorch"<tsn-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"君临天下"<1058847739@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/tsn-pytorch] trained models in pytorch (#6)




@YuLengChuanJiang @shijubushiju Have you extracted optical flow from videos and make lists?
 Otherwise, you should follow this repository to do this.
 This repo is the original version of TSN, coded by Caffe.

**Comment by Shumpei-Kikuta** [comment]
@YuLengChuanJiang The list you get after extracting optical flow is somewhat different from the list you mentioned.
Its columns looks like frame path, video frame number, and video groundtruth class.
If you can't make lists, I recommend using docker image the repo owner's created.

**Comment by YuLengChuanJiang** [comment]
oh, I see . Your reply is so helpful. Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"skhiuk"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午3:28
收件人:&nbsp;"yjxiong/tsn-pytorch"<tsn-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"君临天下"<1058847739@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/tsn-pytorch] trained models in pytorch (#6)




@shijubushiju You should follow here.
 Specifically, the trainlist file should be formed as frame path, video frame number, and video groundtruth class.

**Comment by YuLengChuanJiang** [comment]
OK，i see. maybe I can write a .py to make the list. And I also will try the docker. Thank you very much for your enthusiasm.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"skhiuk"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午3:41
收件人:&nbsp;"yjxiong/tsn-pytorch"<tsn-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"君临天下"<1058847739@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/tsn-pytorch] trained models in pytorch (#6)




@YuLengChuanJiang The list you get after extracting optical flow is somewhat different from the list you mentioned.
 Its columns looks like frame path, video frame number, and video groundtruth class.
 If you can't make lists, I recommend using docker image the repo owner's created.

**Comment by YuLengChuanJiang** [comment]
ok, My email is 1058847739@qq.com.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shijubushiju"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午3:35
收件人:&nbsp;"yjxiong/tsn-pytorch"<tsn-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"君临天下"<1058847739@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjxiong/tsn-pytorch] trained models in pytorch (#6)




@YuLengChuanJiang My email is 1462753330@qq.com, we can discuss these issues

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta I ran the code for pytorch, and now I have calculated the RGB and the optoflow diagram using other methods. I ran the generated list script command bash scripts/build_file_list.sh ucf101 FRAME_PATH for caffe alone. Can I generate a list of files suitable for pytorch

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju You need to build caffe to use `scripts/build_file_list.sh`.
Otherwise, you need to write the appropriate list file, whose columns are frame path, video frame number, and video groundtruth class.
It is not hard.

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta 
Such as my frame path '/ home/dl123 / data/RGB/action/kick/'
Video path for '/ home/dl123 / data/video/action/kick. Avi'
 Optical Flow Images path for '/ home/dl123 / data/flow/action/kick_x/' and'/home/dl123 / data/flow/action/kick_y/'
I have 6 types of action, kick is one of them, its frame number is 123, if I write my own list, is that right:
/ home/dl123 / data/RGB/action/kick /         123             6

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju It seems right to me.
Have you run the program?

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta 
Not yet. Since I failed to install mmaction and denseflow when extracting the optical flow diagram, I tried other methods to get the optical flow image, but I encountered difficulties when generating the train_list in the next step. I was trying to solve this problem. Do you have a good way to help me？

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju I understand.
You just try to use Docker image the repo owner provides us.
You should extract optical flow and make lists as README says.
If you don't follow the optical flow extraction like this repo, you won't get compatible accuracy.

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta 
Do you mean that I use the Docker image provided by the author to generate my list? I noticed that there is a build_file_list.py file in the tools folder in caffe code. Can I use it to generate my training list?

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta 
Do you mean that I use the Docker image provided by the author to generate my list? I noticed that there is a build_file_list.py file in the tools folder in caffe code. Can I use it to generate my training list?

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju Sorry, i mean you should use the docker image.

**Comment by shijubushiju** [comment]
@Shumpei-Kikuta
 I have successfully installed Docker and nvidia-docker, and built the container with the command :docker pull bitxiong/ TSN.
 How can I use it for my own datasets?

**Comment by Shumpei-Kikuta** [comment]
@shijubushiju Congratulations!
Just run the docker container and enter it by executing `docker exec -it [container id] /bin/bash`.
I think you should mount the volume of your local files to the docker container by using `-v` option when running.
Once entering, you can follow README.

**Comment by vivva** [comment]
> @poppingcode I followed the [instructions](https://github.com/yjxiong/temporal-segment-networks#testing-provided-models) at the original TSN repository. Just copied the [eval_scores.py](https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_scores.py) file provided there in conjunction with the folder [pyActionRecog](https://github.com/yjxiong/temporal-segment-networks/tree/master/pyActionRecog) which is needed as a dependency.
> 
> Hope it works fine for you!

 Have you changed anything? I did as you said, but it would report an error. 
this is my print
score_npz_files: [119547037146038801333356, 119547037146038801333356]

the error
`Traceback (most recent call last):
  File "tools/eval_scores.py", line 33, in <module>
    score_list = [x['scores'][:, 0] for x in score_npz_files]   #init
  File "tools/eval_scores.py", line 33, in <listcomp>
    score_list = [x['scores'][:, 0] for x in score_npz_files]   #init
TypeError: 'int' object is not subscriptable
`
Thank you very much！！

**Comment by poppingcode** [comment]
can you print x['scores'],and check it can be indexed

**Comment by poppingcode** [comment]
@vivva can you print x['scores'],and check it can be indexed

**Comment by nishanthrachakonda** [comment]
> KeyError
@Fairasname how did you fix this error ?

**Comment by YuLengChuanJiang** [comment]
您好！您的邮件我已收到，我会尽快查看并回复 ，请不用担心。 祝您万事如意！     
                                                                   冷川江

**Comment by zhudongwork** [comment]
> Hi @yjxiong, I'm tried to convert PyTorch model to onnx model. But I got this error: RuntimeError: Attempted to trace SegmentConsensus, but tracing of legacy functions is not supported. Have any solution for this?

I had same problem

**Comment by YuLengChuanJiang** [comment]
您好！您的邮件我已收到，我会尽快查看并回复 ，请不用担心。 祝您万事如意！     
                                                                   冷川江
