### ISSUE TITLE
List index out of range in test_models.py

### ISSUE THREAD

**Issue by Mohamad73** [yjxiong/tsn-pytorch#60]
Hello,
I did the training part but when I try to do the test using test_models.py, I get the error below. Any help is appreciated. 
`python test_models.py ucf101 RGB ucf101_rgb_val_list ucf101_bninception__rgb_model_best.pth --arch BNInception --save_scores score_file_name

Initializing TSN with base model: BNInception.
TSN Configurations:
    input_modality:     RGB
    num_segments:       1
    new_length:         1
    consensus_module:   avg
    dropout_ratio:      0.7
        
/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py:514: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
model epoch 40 best prec@1: 78.0861750075
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "test_models.py", line 128, in <module>
    rst = eval_video((i, data, label))
  File "test_models.py", line 116, in eval_video
    rst = net(input_var).data.cpu().numpy().copy()
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 69, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 80, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 38, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 31, in scatter
    return scatter_map(inputs)
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 73, in forward
    streams = [_get_stream(device) for device in ctx.target_gpus]
  File "/home/mohamad/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 100, in _get_stream
    if _streams[device] is None:
IndexError: list index out of range`

**Comment by Mohamad73** [comment]
Closing it as I had just to precise the number of gpus in the test.models.py.

**Comment by immaping** [comment]
I have the same issue,can anyone help me?sir...  @yjxiong

**Comment by immaping** [comment]
How do you solve this issue ?sir... @Mohamad73

**Comment by immaping** [comment]
I have solved this question. Because i have only 1 gpu,i changed workers from "- j 4" to "- j 1",and this issue is removed.
