### ISSUE TITLE
I change loss.data[0] to loss.item(),so error happens

### ISSUE THREAD

**Issue by zhangtao22** [yjxiong/tsn-pytorch#77]
losses.update(loss.item(), input.size(0))
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/aten/src/THC/THCCachingAllocator.cpp:470)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fe82aad0fe1 in /home/zhangtao/.local/lib/python2.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fe82aad0dfa in /home/zhangtao/.local/lib/python2.7/site-packages/torch/lib/libc10.so)

**Comment by zhangtao22** [comment]
main.py:185: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  total_norm = clip_grad_norm(model.parameters(), args.clip_gradient)
Epoch: [0][0/150], lr: 0.00100  Time 7.577 (7.577)      Data 1.916 (1.916)      Loss 4.6146 (4.6146)    Prec@1 1.562 (1.562)  Prec@5 7.812 (7.812)
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [24,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    main()
  File "main.py", line 124, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 174, in train
    losses.update(loss.item(), input.size(0))
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/aten/src/THC/THCCachingAllocator.cpp:470)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fb0956aafe1 in /home/zhangtao/.local/lib/python2.7/site-packages/torch/lib/libc10.so)
